name: Compress and upx nezha-agent

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日午夜运行
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # 添加写入权限
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 安装 UPX
        run: sudo apt-get update && sudo apt-get install -y upx-ucl
      
      - name: 获取最新版本号
        id: get_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/nezhahq/agent/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "获取到的版本号: $LATEST_VERSION"
      
      - name: 下载并解压 AMD64 版本
        run: |
          mkdir -p amd64
          cd amd64
          wget https://github.com/nezhahq/agent/releases/download/${{ steps.get_version.outputs.version }}/nezha-agent_linux_amd64.zip
          unzip -o nezha-agent_linux_amd64.zip
          echo "AMD64 文件列表："
          ls -lh
      
      - name: 下载并解压 ARM64 版本
        run: |
          mkdir -p arm64
          cd arm64
          wget https://github.com/nezhahq/agent/releases/download/${{ steps.get_version.outputs.version }}/nezha-agent_linux_arm64.zip
          unzip -o nezha-agent_linux_arm64.zip
          echo "ARM64 文件列表："
          ls -lh
      
      - name: UPX 压缩
        run: |
          # AMD64 版本
          if [ -f "amd64/nezha-agent" ]; then
            echo "压缩 AMD64 版本..."
            upx -9 amd64/nezha-agent -o swith
            mv swith amd64/swith
            ls -lh amd64/swith
          else
            echo "错误：找不到 AMD64 可执行文件"
            exit 1
          fi
          
          # ARM64 版本
          if [ -f "arm64/nezha-agent" ]; then
            echo "压缩 ARM64 版本..."
            upx -9 arm64/nezha-agent -o swith
            mv swith arm64/swith
            ls -lh arm64/swith
          else
            echo "错误：找不到 ARM64 可执行文件"
            exit 1
          fi

      - name: 检查压缩后的文件
        run: |
          echo "检查压缩后的文件大小："
          ls -lh amd64/swith || echo "AMD64 文件不存在"
          ls -lh arm64/swith || echo "ARM64 文件不存在"
          
          # 检查文件大小是否合理
          for file in amd64/swith arm64/swith; do
            if [ -f "$file" ]; then
              size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file")
              if [ "$size" -lt 5000000 ]; then  # 小于5MB
                echo "错误：$file 文件大小异常 ($size bytes)"
                exit 1
              fi
            fi
          done

      - name: 发布 AMD64 版本
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: amd64
          name: amd64
          files: amd64/swith
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

      - name: 发布 ARM64 版本
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: arm64
          name: arm64
          files: arm64/swith
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
