name: Compress and Release Agent

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日午夜运行
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # 添加写入权限
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 安装 UPX
        run: sudo apt-get update && sudo apt-get install -y upx-ucl
      
      - name: 获取最新版本号
        id: get_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/nezhahq/agent/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "获取到的版本号: $LATEST_VERSION"
      
      - name: 下载并解压 AMD64 版本
        run: |
          wget https://github.com/nezhahq/agent/releases/download/${{ steps.get_version.outputs.version }}/nezha-agent_linux_amd64.zip
          unzip -o nezha-agent_linux_amd64.zip
          # 检查文件大小
          ls -lh nezha-agent_linux_amd64.zip
          ls -lh nezha-agent
      
      - name: 下载并解压 ARM64 版本
        run: |
          wget https://github.com/nezhahq/agent/releases/download/${{ steps.get_version.outputs.version }}/nezha-agent_linux_arm64.zip
          unzip -o nezha-agent_linux_arm64.zip
          # 检查文件大小
          ls -lh nezha-agent_linux_arm64.zip
          ls -lh nezha-agent
      
      - name: UPX 压缩
        run: |
          # AMD64 版本
          if [ -f "nezha-agent" ]; then
            echo "压缩 AMD64 版本..."
            upx -9 nezha-agent -o swith_amd64
            ls -lh swith_amd64
          else
            echo "错误：找不到 AMD64 可执行文件"
            exit 1
          fi
          
          # 备份原文件
          mv nezha-agent nezha-agent.bak
          
          # ARM64 版本
          if [ -f "nezha-agent" ]; then
            echo "压缩 ARM64 版本..."
            upx -9 nezha-agent -o swith_arm64
            ls -lh swith_arm64
          else
            echo "错误：找不到 ARM64 可执行文件"
            exit 1
          fi

      - name: 检查压缩后的文件
        run: |
          echo "检查压缩后的文件大小："
          ls -lh swith_amd64 || echo "AMD64 文件不存在"
          ls -lh swith_arm64 || echo "ARM64 文件不存在"
          
          # 检查文件大小是否合理
          for file in swith_amd64 swith_arm64; do
            if [ -f "$file" ]; then
              size=$(stat -f%z "$file" || stat -c%s "$file")
              if [ "$size" -lt 1000000 ]; then  # 小于1MB
                echo "错误：$file 文件大小异常 ($size bytes)"
                exit 1
              fi
            fi
          done

      - name: 发布 AMD64 版本
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: amd64
          name: AMD64 Release
          files: swith_amd64
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

      - name: 发布 ARM64 版本
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: arm64
          name: ARM64 Release
          files: swith_arm64
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
