name: Compress and Release Agent

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日午夜运行
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # 添加写入权限
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 配置 Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 安装 UPX
        run: sudo apt-get update && sudo apt-get install -y upx-ucl
      
      - name: 获取最新版本号
        id: get_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/nezhahq/agent/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
      
      - name: 下载并解压 AMD64 版本
        run: |
          wget https://github.com/nezhahq/agent/releases/download/${{ steps.get_version.outputs.version }}/nezha-agent_linux_amd64.zip
          unzip -o nezha-agent_linux_amd64.zip
      
      - name: 下载并解压 ARM64 版本
        run: |
          wget https://github.com/nezhahq/agent/releases/download/${{ steps.get_version.outputs.version }}/nezha-agent_linux_arm64.zip
          unzip -o nezha-agent_linux_arm64.zip
      
      - name: UPX 压缩
        run: |
          for file in $(find . -type f -executable); do
            if [[ $file == *"amd64"* ]]; then
              upx -9 "$file" -o swith_amd64
            elif [[ $file == *"arm64"* ]]; then
              upx -9 "$file" -o swith_arm64
            fi
          done

      - name: 发布 AMD64 版本
        uses: softprops/action-gh-release@v1
        with:
          tag_name: amd64
          name: AMD64 Release
          files: swith_amd64
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

      - name: 发布 ARM64 版本
        uses: softprops/action-gh-release@v1
        with:
          tag_name: arm64
          name: ARM64 Release
          files: swith_arm64
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

      - name: 重命名上传的文件
        run: |
          # 下载 AMD64 版本并重命名
          curl -L -o temp_amd64 https://github.com/${{ github.repository }}/releases/download/amd64/swith_amd64
          mv temp_amd64 swith
          gh release upload amd64 swith --clobber
          
          # 下载 ARM64 版本并重命名
          curl -L -o temp_arm64 https://github.com/${{ github.repository }}/releases/download/arm64/swith_arm64
          mv temp_arm64 swith
          gh release upload arm64 swith --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
